# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
  spool:     { type: memory }
  transport: smtp
  host:      smtp.mailtrap.io
  username:  63e2506afbcd23
  password:  2f8de9a7aa63ce
  auth_mode: cram-md5
  port: 2525
